import AccountIcon from "../../Assets/svg/account.svg";
import Logo1 from "../../Assets/png/aanamaak_mart_logo.webp";
import AddIcon from "../../Assets/svg/add.svg";
import BlackClearIcon from "../../Assets/svg/blackClear.svg";
import BusinessDashboard from "../../Assets/svg/BussinessCenter.svg";
import ClearIcon from "../../Assets/svg/clear.svg";
import dashboard_search from "../../Assets/svg/dashboard_search.svg";
import DateRangeIcon from "../../Assets/svg/dateRange.svg";
import DeveloperDashboard from "../../Assets/svg/developerCenter.svg";
import DocumentationIcon from "../../Assets/svg/documentation.svg";
import UploadDownloadIcon from "../../Assets/svg/downloadFile.svg";
import DropDownIcon from "../../Assets/svg/dropDownArrow.svg";
import EditIcon from "../../Assets/svg/edit.svg";
import failure_trans from "../../Assets/svg/failed_trans.svg";
import FinanceDashboard from "../../Assets/svg/financeCenter.svg";
import InvoiceIcon from "../../Assets/svg/invoice.svg";
import ApiKeyIcon from "../../Assets/svg/key.svg";
import NotificationNav from "../../Assets/svg/Notification.svg";
import PaginationIcon from "../../Assets/svg/paginationArrow.svg";
import PasswordHider_Icon from "../../Assets/svg/passwordhide.svg";
import PasswordView_Icon from "../../Assets/svg/passwordvisible.svg";
import RemoveIcon from "../../Assets/svg/remove.svg";
import ReportIcon from "../../Assets/svg/report.svg";
import ReviewIcon from "../../Assets/svg/review.svg";
import success_trans from "../../Assets/svg/success_trans.svg";
import UploadIcon from "../../Assets/svg/upload.svg";
import search_icon from "../../Assets/svg/searchIcon.svg";
import arrow_down from "../../Assets/svg/ArrowDown.svg";
import api_Info_icon from "../../Assets/svg/ApiInfoIcon.svg";
import operation_center from "../../Assets/svg/OperationCenter.svg";
import product_center from "../../Assets/svg/ProductCenter.svg";
import report_center from "../../Assets/svg/ReportCenter.svg";
import creds_eye_icon from "../../Assets/svg/CredsEyeIcon.svg";
import user_setting_icon from "../../Assets/svg/userSettingIcon.svg";
import modal_close_icon from "../../Assets/svg/modalCloseIcon.svg";
import balance_side_icon from "../../Assets/svg/BalanceSideIcon.svg";
import bill_side_icon from "../../Assets/svg/BillSideIcon.svg";
import download_report from "../../Assets/svg/download_report.svg";
import generate_report_icon from "../../Assets/svg/GenerateReportIcon.svg";
import schedule_icon from "../../Assets/svg/SchdulerIcon.svg";
import delete_schedule from "../../Assets/svg/delete_schedule.svg";
import edit_schedule from "../../Assets/svg/edit_schedule.svg";
import product_arrow_icon from "../../Assets/svg/ProductArrowIcon.svg";
import face_recognition from "../../Assets/svg/FaceRecognition.svg";
import customer_Support from "../../Assets/png/customerSupport.png";
import { ReactComponent as profile_icon } from "../../Assets/svg/ProfileIcon.svg";
import { ReactComponent as setting_icon } from "../../Assets/svg/SettingIcon.svg";
import { ReactComponent as logout_icon } from "../../Assets/svg/LogoutIcon.svg";
import noData from "../../Assets/svg/noData.svg";
import rupee_icon from "../../Assets/png/rupee.png";
import rupeeRecharge_icon from "../../Assets/png/rupeeRecharge.png";
import rupay_icon from "../../Assets/png/rupay.png";
import bank_icon from "../../Assets/png/bank.png";
import copy_icon from "../../Assets/png/copy.png";
import close_icon from "../../Assets/png/close.png";
import three_dots from "../../Assets/png/3dots.png";
import upload_image from "../../Assets/png/upload.png";
import creds_eye_close_icon from "../../Assets/png/eyeclose.png";
import face_id from "../../Assets/png/face-id.png";
import Profilex_Logo from "../../Assets/svg/ProfilexLogo.svg";
import Profilex_Image from "../../Assets/svg/ProfilexImage.svg";
import back_Arrow_Terms from "../../Assets/svg/backArrowTerms.svg";

export const LogoFinal = Logo1;
export const FinanceCenter = FinanceDashboard;
export const DeveloperCenter = DeveloperDashboard;
export const BusinessCenter = BusinessDashboard;
export const OperationCenter = operation_center;
export const ProductCenter = product_center;
export const ReportCenter = report_center;
export const Notification = NotificationNav;
export const Dropdown = DropDownIcon;
export const DateRange = DateRangeIcon;
export const Invoice = InvoiceIcon;
export const Report = ReportIcon;
export const Documenatation = DocumentationIcon;
export const ApiKey = ApiKeyIcon;
export const Account = AccountIcon;
export const Add = AddIcon;
export const Upload = UploadIcon;
export const UploadDownload = UploadDownloadIcon;
export const Remove = RemoveIcon;
export const Review = ReviewIcon;
export const Clear = ClearIcon;
export const BlackClear = BlackClearIcon;
export const Edit = EditIcon;
export const PaginationArrow = PaginationIcon;
export const PasswordHide = PasswordHider_Icon;
export const PasswordView = PasswordView_Icon;
export const FailedTransaction = failure_trans;
export const SuccessTransaction = success_trans;
export const DashboardSearchIcon = dashboard_search;
export const SearchIcon = search_icon;
export const ArrowDown = arrow_down;
export const ApiInfoIcon = api_Info_icon;
export const CredsEyeIcon = creds_eye_icon;
export const UserSettingIcon = user_setting_icon;
export const ModalCloseIcon = modal_close_icon;
export const BalanceSideIcon = balance_side_icon;
export const BillSideIcon = bill_side_icon;
export const DownloadReport = download_report;
export const GeneratedReportIcon = generate_report_icon;
export const ScheduleIcon = schedule_icon;
export const ScheduleDelete = delete_schedule;
export const ScheduleEdit = edit_schedule;
export const ProductArrowIcon = product_arrow_icon;
export const FaceRecognition = face_recognition;
export const customerSupport = customer_Support;
export const ProfileIcon = profile_icon;
export const SettingIcon = setting_icon;
export const LogoutIcon = logout_icon;
export const NoDataBi = noData;
export const rupee = rupee_icon;
export const rupay = rupay_icon;
export const rupeeRecharge = rupeeRecharge_icon;
export const bank = bank_icon;
export const copy = copy_icon;
export const CloseIcon = close_icon;
export const CredsEyeCloseIcon = creds_eye_close_icon;
export const dots = three_dots;
export const uploadImage = upload_image;
export const faceid = face_id;
export const ProfilexLogo = Profilex_Logo;
export const ProfilexImage = Profilex_Image;
export const BackArrowTerms = back_Arrow_Terms;
